name: PHPUnit

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.3' ]
        include:
          - php: '8.3'
            coverage: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          cache: npm
      - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - run: npm ci
      - name: Authenticate composer to GitHub
        run: composer config --global --auth github-oauth.github.com '${{ secrets.GITHUB_TOKEN }}'
      - run: npx wp-env start ${{ matrix.coverage && '--xdebug=coverage' || '' }}
        env:
          WP_ENV_PHP_VERSION: ${{ matrix.php }}
      - run: npx wp-env run tests-cli -- composer require --dev phpunit/phpunit:^9.6 yoast/phpunit-polyfills:^2.0 --working-dir=/var/www/html --update-with-all-dependencies
      - run: npx wp-env run tests-cli --env-cwd='wp-content/plugins/presence-api' -- /var/www/html/vendor/bin/phpunit ${{ matrix.coverage && '--coverage-clover coverage.xml' || '' }}
      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: phpunit
